### ISSUE TITLE
Problem with autocompletion

### ISSUE THREAD

**Issue by templth** [Gbuomprisco/ngx-chips#509] opened 2017-07-28 21:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
~~[ ] feature request~~ [new feature requests are not considered at this time]
[ ] support request/question
```

**Current behavior**

When using the following code:

```
<tag-input i18n-placeholder="@@fill-languages" placeholder="Fill your languages"
                 i18n-secondaryPlaceholder="@@fill-languages" secondaryPlaceholder="Fill your languages"
                 formControlName="languages" theme="bootstrap"><!-- [onlyFromAutocomplete]="true"-->
  <tag-input-dropdown [autocompleteItems]="[{display: 'Item1', value: 0}, 'item2', 'item3']">
  </tag-input-dropdown>
</tag-input>
```

I have the following error and autocompletion doesn't work:

```
ERROR TypeError: this.inputForm.form.valueChanges.debounceTime is not a function
    at TagInputComponent.setUpTextChangeSubscriber (vendor.bundle.js:10523)
    at TagInputComponent.ngAfterViewInit (vendor.bundle.js:10421)
    at callProviderLifecycles (vendor.bundle.js:76191)
    at callElementProvidersLifecycles (vendor.bundle.js:76166)
    at callLifecycleHooksChildrenFirst (vendor.bundle.js:76150)
    at checkAndUpdateView (vendor.bundle.js:77255)
    at callViewAction (vendor.bundle.js:77612)
    at execComponentViewsAction (vendor.bundle.js:77544)
    at checkAndUpdateView (vendor.bundle.js:77253)
    at callViewAction (vendor.bundle.js:77612)
```

Note that if I comment the `tag-input-dropdown` block, I have no error...

**Expected behavior**

No error message.

**Minimal reproduction of the problem with instructions (if applicable)**

**What do you use to build your app?. Please specify the version**

angular-cli 1.2.4

**Angular version:** 

4.3.1

**ngx-chips version:**

1.4.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chromz

**Comment by Gbuomprisco** [comment] 2017-07-31 12:30
Seems a dupe of https://github.com/Gbuomprisco/ngx-chips/issues/499.

Can you make sure you can require debounceTime from rxjs? as you can see, the operator is required to be in your deps.

**Closed** 2017-08-04 12:31 UTC
