### ISSUE TITLE
Aot build not working at runtime. Compile ok

### ISSUE THREAD

**Issue by thaoula** [Gbuomprisco/ngx-chips#532] opened 2017-08-11 07:16 UTC
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```
**Current behavior**

I run ng build --aot --prod 

Everything builds ok. Load the browser and i get the following error -

Uncaught TypeError: Cannot read property 'a' of undefined
    at Object.oxwE (vendor.5f1aa5be4ea3e26d6f6b.bundle.js:1)
    at n (inline.72edfe5b499c9a2ff67a.bundle.js:1)
    at Object.+nms (vendor.5f1aa5be4ea3e26d6f6b.bundle.js:1)
    at n (inline.72edfe5b499c9a2ff67a.bundle.js:1)
    at Object.DrDF (main.61b83aedd0f38c85e610.bundle.js:1)
    at n (inline.72edfe5b499c9a2ff67a.bundle.js:1)
    at Object.0 (main.61b83aedd0f38c85e610.bundle.js:1)
    at n (inline.72edfe5b499c9a2ff67a.bundle.js:1)
    at window.webpackJsonp (inline.72edfe5b499c9a2ff67a.bundle.js:1)
    at main.61b83aedd0f38c85e610.bundle.js:1**

This error appears very similar to this issue -
https://github.com/Gbuomprisco/ngx-chips/issues/526

At the moment i am using the following npm reference as a workaround:
"ngx-chips": "jknisley/ngx-chips",

**Expected behavior**

The page should load normally and display the components.

**Minimal reproduction of the problem with instructions (if applicable)**

ng new
npm install ngx-chips
add component that uses ngx-chips
ng build --prod --aot 
view error in browser

**What do you use to build your app?. Please specify the version**

angular cli 1.3.0

**Angular version:** 

angular 4.3.0-4.3.4

**ngx-chips version:**

1.4.7-1.5.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

**Comment by FriOne** [comment] 2017-08-11 10:48
Same here, the problem is in angular CLI 1.3.0

**Comment by Gbuomprisco** [comment] 2017-08-11 11:01
Hi both, I'm fairly sure it's the same issue, so I'll close this. Please follow that thread for updates

**Closed by Gbuomprisco** 2017-08-11 11:01 UTC
