### ISSUE TITLE
Prod build failed 

### ISSUE THREAD

**Issue by Farzannajipour** [Gbuomprisco/ngx-chips#912] opened 2019-11-04 15:46 UTC
PLEASE MAKE SURE THAT:
- you searched similar issues online (9/10 issues in this repo are solved by googling, so please...do it)
- you provide an online demo I can see without having to replicate your environment
- you help me by debugging your issue, and if you can't, do go on filling out this form

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] support request/question

Notice: feature requests will be ignored, submit a PR if you'd like
```

**Current behavior**

I want to build with this command:

`ng build --aot=true --prod --build-optimizer --configuration=dev --outputHashing=all`

But I got this error:

`ERROR in ./node_modules/ng2-material-dropdown/fesm5/ng2-material-dropdown.js`

`TypeError: Cannot read property 'kind' of undefined at isAngularDecoratorMetadataExpression`

**Expected behavior**

Run like dev & staging mode

**Minimal reproduction of the problem with instructions (if applicable)**

Download Angular 8,  install ngx chips

**What do you use to build your app?. Please specify the version**

Angular-CLI

**Angular version:** 

 8.2.0.

**ngx-chips version:**

2.0.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment] 2019-11-04 16:58
Hi, have you also tried v2.1.0?

**Comment by tidusjar** [comment] 2019-11-06 09:27
I am also having the same issue on V2.1.0

```
ERROR in ./node_modules/ng2-material-dropdown/fesm5/ng2-material-dropdown.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\_git\OmbiV4\Ombi\src\Ombi\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)
```

**Comment by Farzannajipour** [comment] 2019-11-10 10:46
> Hi, have you also tried v2.1.0?

Yes, I've tried v2.1.0 but it does not change anything

**Comment by Moulde** [comment] 2019-11-11 12:16
I have the same issue.
@tidusjar While it is the exact same error message i get, I don't understand what the connection is from this library, to the ng-multiselect-dropdown repo?
This repo seems to depend on ng2-material-dropdown and not the above?

**Comment by IvanWSM** [comment] 2019-11-12 22:48
Is there any solution yet for this? Specifically the `ng2-material-dropdown` dependency issue; I'm unable to build production bundle, and removing the package is not really an option at this point

**Comment by Gbuomprisco** [comment] 2019-11-12 23:44
Hi, I'm gonna take a look during the weekend, hope to fix it

**Comment by staticbuzz** [comment] 2019-11-13 03:51
Same issue here

**Comment by Farzannajipour** [comment] 2019-11-13 08:55
> Hi, I'm gonna take a look during the weekend, hope to fix it

Thank you Giancarlo

**Comment by IvanWSM** [comment] 2019-11-13 14:44
> Hi, I'm gonna take a look during the weekend, hope to fix it

Thank you so much, waiting for it :)

**Comment by nadeemse** [comment] 2019-11-13 18:01
I am also facing the same issue, any luck ? 
ERROR in ./node_modules/ng2-material-dropdown/fesm2015/ng2-material-dropdown.js

**Comment by IvanWSM** [comment] 2019-11-13 18:07
> I am also facing the same issue, any luck ?
> ERROR in ./node_modules/ng2-material-dropdown/fesm2015/ng2-material-dropdown.js

According to @Gbuomprisco, he'll take a look at it on the weekend, so let's wait for now; I recommend also checking the issue on the `ng2-material-dropdown` repo to see if we get any other update on the matter, since the issue itself seems to be on that package instead of `ngx-chips` per se.

[Issue](https://github.com/Gbuomprisco/ng2-material-dropdown/issues/66) on Ng2-Material-Dropdown repo.

**Comment by Gbuomprisco** [comment] 2019-11-17 20:01
Hi everyone, I had a look at the issue as promised: my build can't reproduce the issue you all have; also had a look at the other package's issue. My gut feeling is that it may be due to a package version (angular-devkit/build-angular):
- this is the version I use to build on v9: "@angular-devkit/build-angular": "^0.803.19"
- this is the version I use to build on v9": "@angular-devkit/build-angular": "^0.803.8"

Can you try to use the same versions as above? Or share which exact versions you're using?

**Comment by Marcelh1983** [comment] 2019-11-18 08:04
I had the same [issue](https://github.com/Marcelh1983/angular-document-viewer/issues/10) with my library. Seems like updating the @angular/cli solves the problem. I found more related issues: [@angular/cli](https://github.com/angular/angular-cli/issues/13172) [ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill/issues/573) but haven't found a way to create a package that both works on previous and latest @angular/cli version

**Comment by vcondratiev** [comment] 2019-11-18 11:16
> Hi everyone, I had a look at the issue as promised: my build can't reproduce the issue you all have; also had a look at the other package's issue.
> 
> My gut feeling is that it may be due to a package version (angular-devkit/build-angular):
> 
> * this is the version I use to build on v9: "@angular-devkit/build-angular": "^0.803.19"
> * this is the version I use to build on v8": "@angular-devkit/build-angular": "^0.803.8"
> 
> Can you try to use the same versions as above? Or share which exact versions you're using?

Changing the version to the one you used for v8 work for me. Thank you

**Comment by Gbuomprisco** [comment] 2019-11-18 14:11
Nice, if someone else can confirm, I'll close the issue

**Comment by IvanWSM** [comment] 2019-11-18 14:53
> Nice, if someone else can confirm, I'll close the issue

Confirming changing `"@angular-devkit/build-angular": "~0.800.0"` to `~0.803.8` solved the issue :)

Thank you a lot!

**Closed** 2019-11-18 17:18 UTC

**Comment by evoytenkoapps** [comment] 2020-01-16 08:55
I had same problem. I set `"buildOptimizer": false` in  `angular.json` for production , and is ok.
thx for [https://github.com/ckeditor/ckeditor4-angular/issues/78](https://github.com/ckeditor/ckeditor4-angular/issues/78)

**Comment by Gbuomprisco** [comment] 2020-01-16 13:41
That's not really a solution, buildOptimzer is an important setting. If you set the correct versions the problem should be solved

**Comment by radiumrasheed** [comment] 2020-03-04 06:25
> Hi everyone, I had a look at the issue as promised: my build can't reproduce the issue you all have; also had a look at the other package's issue.
> 
> My gut feeling is that it may be due to a package version (angular-devkit/build-angular):
> 
> * this is the version I use to build on v9: "@angular-devkit/build-angular": "^0.803.19"
> * this is the version I use to build on v8": "@angular-devkit/build-angular": "^0.803.8"
> 
> Can you try to use the same versions as above? Or share which exact versions you're using?

@Gbuomprisco  is this supposed to support angularv6 ?

**Comment by Gbuomprisco** [comment] 2020-03-04 06:36
Yes AFAIK it shouldn't have issues as long as the dependencies are correct
