### ISSUE TITLE
animation error: The provided timing value "" is invalid.

### ISSUE THREAD

**Issue by jamalx31** [Gbuomprisco/ngx-chips#490] opened 2017-07-11 20:25 UTC
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
throws the error
```
ERROR Error: Unable to process animations due to the following failed trigger transitions
@animation has failed due to:
- Please provide a value for the animation param enter
- The provided timing value "" is invalid.
```

**Expected behavior**
no errors

**Minimal reproduction of the problem with instructions (if applicable)**
`<tag-input [(ngModel)]="tags" ></tag-input>`

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular/cli: 1.0.0
node: 7.7.3

**Angular version:** 
^4

**ng2-tag-input version:**
"ngx-chips": "^1.4.5"

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by Gbuomprisco** [comment] 2017-07-11 20:40
What precise angular version are you using?

**Comment by reco** [comment] 2017-07-11 21:21
i work with jamal. we use

@angular/cli: 1.2.0
node: 7.10.0
os: darwin x64
@angular/animations: 4.2.6
@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.2.0
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/flex-layout: 2.0.0-beta.7
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/language-service: 4.2.6

**Comment by Gbuomprisco** [comment] 2017-07-11 21:56
I'll have a look at this soon, for now try downgrading to 1.4.5-beta

**Comment by reco** [comment] 2017-07-11 23:52
same problem with `ngx-chips@1.4.5-beta`

```
ERROR Error: Unable to process animations due to the following failed trigger transitions
@animation has failed due to:
- Please provide a value for the animation param enter
- The provided timing value "" is invalid.
```

**Comment by Gbuomprisco** [comment] 2017-07-12 07:08
I don't seem able to reproduce

**Comment by reco** [comment] 2017-07-12 15:12
we have the same issue on `ngx-chips@1.4.5-beta` and `ngx-chips@1.4.4`.

**Comment by feliksg** [comment] 2017-07-12 16:23
I have the same issue with
```
"@angular/animations": "^4.2.6",
"ngx-chips": "^1.4.5"
```

**Comment by dlhdesign** [comment] 2017-07-12 18:54
I get this on `ngx-chips@1.4.5` when I initiate the tag-input with an initial value. When no initial value is present, the error is not shown.

Note that I also received the error on every add/remove of an item when I set the `animationDuration` key without binding it (ex: `... animationDuration="{enter:'0ms',leave:'0ms'}" ...`). When I bound it, the string value is converted to the required object (ex: `... [animationDuration]="{enter:'0ms',leave:'0ms'}" ...`).

**Comment by Gbuomprisco** [comment] 2017-07-12 19:10
alright, I think I'll need to update the animations in https://github.com/Gbuomprisco/ng2-material-dropdown/blob/master/src/modules/components/menu/ng2-dropdown-menu.ts#L30

**Comment by feliksg** [comment] 2017-07-15 12:59
@Gbuomprisco Would you be able to push this fix (85ddc7a6d5ef300eaaf37bf5cf4e5dae4b1626cf) up to npm please? I believe that resolves our issue.

**Comment by jamalx31** [comment] 2017-07-17 11:42
@Gbuomprisco please update us when you do

**Comment by Gbuomprisco** [comment] 2017-07-17 11:48
1.4.6 is out but does not solve the animations issue

**Comment by mszpereira** [comment] 2017-07-26 16:51
Is there any info or workaround available for this issue?

**Comment by skix123** [comment] 2017-08-01 07:02
Any updates?

**Comment by Gbuomprisco** [comment] 2017-08-04 12:35
Hi guys can anyone check if you still have the same issue with v1.4.7?

**Comment by mszpereira** [comment] 2017-08-04 16:50
I'll try it, just a second and i'll edit this comment.

**Comment by feliksg** [comment] 2017-08-04 16:59
I can also confirm what @mszpereira stated

**Comment by mszpereira** [comment] 2017-08-05 17:37
Even tought i did import BrowserAnimationsModule in my app.module file, when using this new option to disable animation, i somehow got:

**Error: Found the synthetic property @.disabled. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.**

**Comment by Gbuomprisco** [comment] 2017-08-05 21:05
Please include a plunkr, I can't really help without knowing your setup in fully detail.

**Comment by dlhdesign** [comment] 2017-08-05 22:07
https://plnkr.co/edit/Wu9qw8?p=preview

**Comment by Gbuomprisco** [comment] 2017-08-06 00:10
Exact, if you use ngModel, it seems that does not happen

**Comment by Gbuomprisco** [comment] 2017-08-06 11:44
This https://github.com/Gbuomprisco/ngx-chips/pull/519 should solve it guys

**Comment by Gbuomprisco** [comment] 2017-08-06 11:49
v1.4.8 is out - if anyone could check, it would be great!

**Comment by feliksg** [comment] 2017-08-06 12:24
@Gbuomprisco 1.4.8 resolved the issue for me, thanks so much!

**Comment by Gbuomprisco** [comment] 2017-08-06 12:28
Great, closing as I hope it will work for everyone

**Closed by Gbuomprisco** 2017-08-06 12:28 UTC

**Comment by dlhdesign** [comment] 2017-08-07 19:02
Now getting this:
`ERROR TypeError: _this.autocompleteObservable(...).first is not a function
    at TagInputDropdown.getItemsFromObservable (ngx-chips.bundle.js:1309)`

**Comment by Gbuomprisco** [comment] 2017-08-07 19:32
https://plnkr.co/edit/8Yl41KUksqOLNJQEypsM?p=preview

ngx-chips requires these peer deps:

```
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/first';
import 'rxjs/add/operator/debounceTime';
```

**Comment by dlhdesign** [comment] 2017-08-07 19:37
Gotcha; I was missing `first` in my environment. 1.4.8 works for me on the reported issue; thanks!

**Comment by Gbuomprisco** [comment] 2017-08-07 19:40
yeah i should add it to the package.json actually

**Comment by hxdef2517** [comment] 2017-12-23 10:00
Still got this issue with 1.4.7
