### ISSUE TITLE
Even with onlyFromAutocomplete=true, other values are getting added.

### ISSUE THREAD

**Issue by sankukatti** [Gbuomprisco/ngx-chips#689] opened 2018-03-07 04:38 UTC
**My Code**

```
<!-- Input for selecting users -->
              <tag-input inputClass="autoCompInput" [(ngModel)]="answers[question._id]['connections']"
                         maxItems="10" [identifyBy]="'_id'" [displayBy]="'profileDetails.email'"
                         [onlyFromAutocomplete]="true"
                         placeholder="Type the name here to select..."
                         secondaryPlaceholder="Type the name here to select...">

                <!--Autocomplete options - Probable Connections-->
                <tag-input-dropdown [showDropdownIfEmpty]="true"
                                    [autocompleteItems]="probableConnections">
                </tag-input-dropdown>
              </tag-input>
```

**Comment by Gbuomprisco** [comment] 2018-03-07 08:56
Can't reproduce. Please post an online demo. Closing because template is missing.

**Closed by Gbuomprisco** 2018-03-07 08:56 UTC
